---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels: {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "api.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.image.api }}
          image: {{ include "api.apiImage" . | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "api.fullname" . | quote }}
      initContainers:
        - name: {{ .Values.image.initApi }}
          image: {{ include "api.initApiImage" . | quote }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ include "api.fullname" . | quote }}
---
