---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testapi-config
  labels:
    helm.sh/chart: api-1.0.0-0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: testapi
    app.kubernetes.io/version: "1.0.0-0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: frontend
data:
  MONGO__AUTHDB: admin
  MONGO__USER: root
  MONGO__PASSWORD: test
  MONGO__HOST: mongodb
  MONGO__PORT: "27017"
  MONGO__DB: management
  MONGO__SELECTTIMEOUTMS: "1000"
---
