---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
  labels:
    helm.sh/chart: api-1.0.0-0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: testapi
    app.kubernetes.io/version: "1.0.0-0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: testapi
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        helm.sh/chart: api-1.0.0-0
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: testapi
        app.kubernetes.io/version: "1.0.0-0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: api
          image: "valeriymolchanov/testapi:1.0.0-0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: testapi-config
      initContainers:
        - name: init-api
          image: valeriymolchanov/init-testapi:1.0.0-0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: testapi-config
---

