replicaCount: 3

imagePullSecrets: []

image:
  repository: valeriymolchanov
  api: testapi
  initApi: init-testapi
  pullPolicy: IfNotPresent

db:
  name: management
  selectTimeoutMs: 1000

mongodb:
  mongodbRootPassword: "test"
  service:
    port: 27017

service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 8081