replicaCount: 3

imagePullSecrets: []

image:
  repository: valeriymolchanov
  api: testapi
  initApi: init-testapi
  pullPolicy: IfNotPresent

db:
  name: management
  selectTimeoutMs: 1000

mongodb:
  mongodbRootPassword: "test"
  service:
    name: api-mongodb
    port: 27017
