replicaCount: 3

imagePullSecrets: []

image:
  repository: valeriymolchanov/testapi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

db:
  host: api-db-svc
  port: 27017
  user: root
  password: test
  selectTimeoutMS: 1000
